name: flutter_shortcuts_example
description: Demonstrates how to use the flutter_shortcuts plugin.
publish_to: "none"

environment:
  flutter: '>=3.35.0'
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_shortcuts:
    # When depending on this package from a real application you should use:
    #   flutter_shortcuts: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/svg/
