name: flutter_shortcuts
description: Flutter plugin for creating static & dynamic app/conversation shortcuts on home screen.
version: 1.4.0
publish_to: "none"

environment:
  flutter: ">=3.35.0"
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.divyanshushekhar.flutter_shortcuts
        pluginClass: FlutterShortcutsPlugin
      ios:
        pluginClass: FlutterShortcutsPlugin
